/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EquipmentSlugRouteImport } from './routes/equipment.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminEquipmentIndexRouteImport } from './routes/admin.equipment.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as EquipmentCategorySlugRouteImport } from './routes/equipment.category.$slug'
import { Route as AdminEquipmentNewRouteImport } from './routes/admin.equipment.new'
import { Route as AdminBookingsIdRouteImport } from './routes/admin.bookings.$id'
import { Route as AdminEquipmentIdEditRouteImport } from './routes/admin.equipment.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EquipmentSlugRoute = EquipmentSlugRouteImport.update({
  id: '/equipment/$slug',
  path: '/equipment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipmentIndexRoute = AdminEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const EquipmentCategorySlugRoute = EquipmentCategorySlugRouteImport.update({
  id: '/equipment/category/$slug',
  path: '/equipment/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipmentNewRoute = AdminEquipmentNewRouteImport.update({
  id: '/equipment/new',
  path: '/equipment/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipmentIdEditRoute = AdminEquipmentIdEditRouteImport.update({
  id: '/equipment/$id/edit',
  path: '/equipment/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/equipment/new': typeof AdminEquipmentNewRoute
  '/equipment/category/$slug': typeof EquipmentCategorySlugRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/equipment/': typeof AdminEquipmentIndexRoute
  '/admin/equipment/$id/edit': typeof AdminEquipmentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/admin': typeof AdminIndexRoute
  '/equipment': typeof EquipmentIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/equipment/new': typeof AdminEquipmentNewRoute
  '/equipment/category/$slug': typeof EquipmentCategorySlugRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/equipment': typeof AdminEquipmentIndexRoute
  '/admin/equipment/$id/edit': typeof AdminEquipmentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/equipment/new': typeof AdminEquipmentNewRoute
  '/equipment/category/$slug': typeof EquipmentCategorySlugRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/equipment/': typeof AdminEquipmentIndexRoute
  '/admin/equipment/$id/edit': typeof AdminEquipmentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/cart'
    | '/login'
    | '/my-bookings'
    | '/register'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/quotes'
    | '/admin/settings'
    | '/equipment/$slug'
    | '/admin/'
    | '/equipment/'
    | '/admin/bookings/$id'
    | '/admin/equipment/new'
    | '/equipment/category/$slug'
    | '/admin/bookings/'
    | '/admin/equipment/'
    | '/admin/equipment/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/cart'
    | '/login'
    | '/my-bookings'
    | '/register'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/quotes'
    | '/admin/settings'
    | '/equipment/$slug'
    | '/admin'
    | '/equipment'
    | '/admin/bookings/$id'
    | '/admin/equipment/new'
    | '/equipment/category/$slug'
    | '/admin/bookings'
    | '/admin/equipment'
    | '/admin/equipment/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/cart'
    | '/login'
    | '/my-bookings'
    | '/register'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/quotes'
    | '/admin/settings'
    | '/equipment/$slug'
    | '/admin/'
    | '/equipment/'
    | '/admin/bookings/$id'
    | '/admin/equipment/new'
    | '/equipment/category/$slug'
    | '/admin/bookings/'
    | '/admin/equipment/'
    | '/admin/equipment/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  RegisterRoute: typeof RegisterRoute
  EquipmentSlugRoute: typeof EquipmentSlugRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  EquipmentCategorySlugRoute: typeof EquipmentCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/equipment/$slug': {
      id: '/equipment/$slug'
      path: '/equipment/$slug'
      fullPath: '/equipment/$slug'
      preLoaderRoute: typeof EquipmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipment/': {
      id: '/admin/equipment/'
      path: '/equipment'
      fullPath: '/admin/equipment/'
      preLoaderRoute: typeof AdminEquipmentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/equipment/category/$slug': {
      id: '/equipment/category/$slug'
      path: '/equipment/category/$slug'
      fullPath: '/equipment/category/$slug'
      preLoaderRoute: typeof EquipmentCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipment/new': {
      id: '/admin/equipment/new'
      path: '/equipment/new'
      fullPath: '/admin/equipment/new'
      preLoaderRoute: typeof AdminEquipmentNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipment/$id/edit': {
      id: '/admin/equipment/$id/edit'
      path: '/equipment/$id/edit'
      fullPath: '/admin/equipment/$id/edit'
      preLoaderRoute: typeof AdminEquipmentIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminEquipmentNewRoute: typeof AdminEquipmentNewRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminEquipmentIndexRoute: typeof AdminEquipmentIndexRoute
  AdminEquipmentIdEditRoute: typeof AdminEquipmentIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminEquipmentNewRoute: AdminEquipmentNewRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminEquipmentIndexRoute: AdminEquipmentIndexRoute,
  AdminEquipmentIdEditRoute: AdminEquipmentIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  RegisterRoute: RegisterRoute,
  EquipmentSlugRoute: EquipmentSlugRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  EquipmentCategorySlugRoute: EquipmentCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
